### ISSUE TITLE
Support for ACL Categories for BF.* commands

### ISSUE THREAD

**Issue by KarthikSubbarao** [valkey-io/valkey-bloom#11]
BF.* commands should have a new "@bloom" ACL Category such that clients authenticated as a user with "@bloom" permissions can execute these commands.

This can be implemented using the valkey-module-rs SDK changes implemented from this issue: https://github.com/valkey-io/valkeymodule-rs/issues/96

**Comment by zackcam** [comment]
Hi - I'd like to start working on this in conjunction with [valkey-io/valkeymodule-rs#96](https://github.com/valkey-io/valkeymodule-rs/issues/96), can this be assigned to me as well.
