### ISSUE TITLE
Support for INFO MODULES

### ISSUE THREAD

**Issue by KarthikSubbarao** [valkey-io/valkey-bloom#12]
Modules can support the INFO ALL / INFO MODULES command by implementing a callback function that writes into the INFO command response.

The bloom module will need to track information such as: Number of bloom objects, Number of Filters across all objects, and total memory used (bytes) by all the bloom objects.

This information can be added as a result into a new INFO section.

Example: https://github.com/valkey-io/valkeymodule-rs/blob/main/examples/info_handler_builder.rs#L9

**Comment by zackcam** [comment]
Hi, I was wondering if this issue could be assigned to me. I created a PR that adds info support.
