### ISSUE TITLE
Support for the DIGEST module data type callback

### ISSUE THREAD

**Issue by KarthikSubbarao** [valkey-io/valkey-bloom#9]
Modules can support the `DEBUG` command on Module data type objects by implementing a Module data type callback. valkey-bloom implements a DIGEST Module data type callback and during a DEBUG operation, we would want to create and return a DIGEST.

This issue will add DIGEST support to the ValkeyModule-rs SDK with which DIGEST support can be added to valkey-bloom
https://github.com/valkey-io/valkeymodule-rs/issues/97

**Comment by nnmehta** [comment]
Will pick this up
